#!/usr/bin/env bash

LGTC_FLASH_FILE="/etc/lgtc/lgtc-first-boot"

if [ -f "$LGTC_FLASH_FILE" ] ; then
    # set machine_id
    ID=`sna-lgtc-getid`
    echo "$ID" > /var/lib/dbus/machine-id
    echo "$ID" > /etc/machine-id
    
    # format SD card and add it to /etc/fstab
    if [ ! -e /dev/mmcblk0 ]; then
      echo "SD card not found!" 1>&2
      exit 1
    fi

    echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/mmcblk0

    if [ $? -ne 0 ]; then
      exit 1
    else
      mkfs.ext4 -F /dev/mmcblk0p1
    fi

    mkdir -p /media/sdcard

    mount /dev/mmcblk0p1 /media/sdcard/
    if [ $? -ne 0 ]; then
      rmdir /media/sdcard
      exit 1
    fi

    echo "/dev/mmcblk0p1    /media/sdcard    ext4    defaults,nofail    0    0" >> /etc/fstab

    # remove flash file
    rm "$LGTC_FLASH_FILE"
fi

# set IP address as hostname
IP=`ip addr show wlan0 | grep -Po 'inet \K[\d.]+'`

echo "${IP//[.]/-}"

if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    /bin/hostname "${IP//[.]/-}"
else
    echo "failed to set hostname"
    exit 1
fi
