#!/usr/bin/env bash

. /etc/videk/conf

LGTC_FLASH_FILE="/etc/lgtc/lgtc-first-boot"

if [ -f "$LGTC_FLASH_FILE" ] ; then
    # set machine_id
    ID=`sna-lgtc-getid`
    echo "$ID" > /var/lib/dbus/machine-id
    echo "$ID" > /etc/machine-id
    
    MMC="/dev/mmcblk0"

    # do not format if it is mounted
    if grep -qs "$MMC" /proc/mounts; then
        echo "$MMC is mounted!"
        exit 1
    fi
    
    # format SD card and add it to /etc/fstab
    if [ ! -e "$MMC" ]; then
        echo "SD card not found!" 1>&2
        exit 1
    fi

    echo -e "o\nn\np\n1\n\n\nw" | fdisk "$MMC"

    if [ $? -ne 0 ]; then
        exit 1
    else
        mkfs.ext4 -F "$MMC"p1
    fi

    mkdir -p /media/sdcard

    mount "$MMC"p1 /media/sdcard/
    if [ $? -ne 0 ]; then
        rmdir /media/sdcard
        exit 1
    fi

    echo "$MMC""p1    /media/sdcard    ext4    defaults,nofail    0    0" >> /etc/fstab

    # remove flash file
    rm "$LGTC_FLASH_FILE"
fi
